#!/usr/bin/env ruby

$LOAD_PATH << "#{ENV['SCRINIUM_ESM_DIAG_ROOT']}/framework"
require 'scrinium_esm_diag_framework'

ScriniumEsmDiag::ConfigManager.parse ARGV[0]

ScriniumEsmDiag::DataflowManager.run
