$LOAD_PATH << "#{ENV['ESMDIAG_ROOT']}/framework"

require 'pp'
require 'digest'
require 'forwardable'
require 'fileutils'
require 'json'
require 'date'

require 'runtime/cli'
require 'runtime/run'
require 'runtime/config_item'
require 'runtime/config_manager'
require 'runtime/cache'
require 'runtime/attached_variables'
require 'actions/action_helpers'
require 'actions/remove_annual_cycle'
require 'actions/anomaly'
require 'actions/extract'
require 'actions/detrend'
require 'actions/filter'
require 'actions/vinterp'
require 'actions/area_avg'
require 'actions/lat_avg'
require 'actions/lon_avg'
require 'dataflow/dataset'
require 'dataflow/dataflow_dsl'
require 'dataflow/dataflow'
require 'dataflow/dataflow_manager'
require 'diagflow/figure.rb'
require 'diagflow/diagflow_dsl'
require 'diagflow/diagflow'
require 'diagflow/diagflow_manager'
